### ISSUE TITLE
Replace usage of `kustomize edit add resource` in the notebooks with an alternative

### ISSUE THREAD

**Issue by HumairAK** [operate-first/hitchhikers-guide#111]
`kustomize` cli will reformat the file and also append changes to at the bottom, this makes `kustomization.yaml` files like the ones [here](https://github.com/operate-first/apps/blob/master/cluster-scope/overlays/prod/moc/smaug/kustomization.yaml) really hard to read (we alphabetically sort these for human readability). 

One instance where this has already caused some issues can be found here: https://github.com/operate-first/apps/pull/1236

**Comment by tumido** [comment]
This is a never ending story and ongoing issue across all history of Operate First. I don't think this is a valid issue.

Yes, kustomize doesn't care about alphabetical order, instead it raises error on duplicate resources and supports a `remove` command. I think we should scrape this alphabetical order idea and rather embrace the component collections proposed by @larsks at https://github.com/operate-first/SRE/issues/369 We can either work hard on tooling and workarounds and scripts to support manual processing of automatically genereated resources or rather focus on going fully automated. I think alphabetical sorting is not important to the machines so we should rather embrace it and work towards more automated solution with less moving parts.

If a standardized tool formats a resource, there's a high chance that the output format is deterministic and if we apply the same tool on the resource again, it results in 0 diff. So if a tool prefers a formatting and we as maintainers can accept that formatting, we should start using it and favor it instead of battling the tools every time on every PR.

Yes, YAML is a whitespaced markup language, but in different flavors/versions/standards it uses different amount of spaces to indent nested properties. Actually even different versions of `kustomize` as well as `kubectl` and `oc` will use either 2 or 4 spaces to indent - all rely on go-yaml library and this is a loong story on its own. There's nothing we should be doing in this case - because patching an already patched tool for a hacked solution is not good pattern. https://github.com/kubernetes-sigs/kustomize/issues/3946 Either go fix it upstream or live with it.

We have a nice saying in Czech for this, not sure about the equivalent in English - "vyrábět narovnávák na ohejbák" - to create a "straightening tool" for a "bender tool" meaning that at first you work hard to bend something and then work even harder to straighten it again... This issue seems like it's suggesting such approach. I think we should invest our energy elsewhere.

**Comment by tumido** [comment]
> I suggest to not use the `opfcli for` that at all.

:+1: to that... less custom tooling is always better.
